// This file will be auto-generated by Supabase CLI in production
// For now, we provide a basic type structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          subscription_plan: string
          subscription_status: string
          trial_ends_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          subscription_plan?: string
          subscription_status?: string
          trial_ends_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          subscription_plan?: string
          subscription_status?: string
          trial_ends_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          org_id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: string
          created_at: string
          last_login_at: string | null
        }
        Insert: {
          id: string
          org_id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: string
          created_at?: string
          last_login_at?: string | null
        }
        Update: {
          id?: string
          org_id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: string
          created_at?: string
          last_login_at?: string | null
        }
      }
      azure_tenants: {
        Row: {
          id: string
          org_id: string
          name: string
          azure_tenant_id: string
          azure_app_id: string
          azure_client_secret: string
          connection_status: string
          last_sync_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          name: string
          azure_tenant_id: string
          azure_app_id: string
          azure_client_secret: string
          connection_status?: string
          last_sync_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          name?: string
          azure_tenant_id?: string
          azure_app_id?: string
          azure_client_secret?: string
          connection_status?: string
          last_sync_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      cost_snapshots: {
        Row: {
          id: string
          org_id: string
          tenant_id: string
          subscription_id: string
          resource_id: string | null
          resource_name: string | null
          resource_type: string | null
          resource_group: string | null
          service_category: string | null
          location: string | null
          cost_usd: number
          date: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          tenant_id: string
          subscription_id: string
          resource_id?: string | null
          resource_name?: string | null
          resource_type?: string | null
          resource_group?: string | null
          service_category?: string | null
          location?: string | null
          cost_usd: number
          date: string
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          tenant_id?: string
          subscription_id?: string
          resource_id?: string | null
          resource_name?: string | null
          resource_type?: string | null
          resource_group?: string | null
          service_category?: string | null
          location?: string | null
          cost_usd?: number
          date?: string
          created_at?: string
        }
      }
      alert_rules: {
        Row: {
          id: string
          org_id: string
          tenant_id: string
          name: string
          type: string
          threshold_amount: number | null
          threshold_percent: number | null
          notification_channels: Json
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          tenant_id: string
          name: string
          type: string
          threshold_amount?: number | null
          threshold_percent?: number | null
          notification_channels: Json
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          tenant_id?: string
          name?: string
          type?: string
          threshold_amount?: number | null
          threshold_percent?: number | null
          notification_channels?: Json
          status?: string
          created_at?: string
          updated_at?: string
        }
      }
      azure_subscriptions: {
        Row: {
          id: string
          tenant_id: string
          subscription_id: string
          name: string
          display_name: string | null
          state: string
          subscription_policies: Json | null
          tags: Json | null
          discovered_at: string
          last_synced_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          subscription_id: string
          name: string
          display_name?: string | null
          state: string
          subscription_policies?: Json | null
          tags?: Json | null
          discovered_at?: string
          last_synced_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          subscription_id?: string
          name?: string
          display_name?: string | null
          state?: string
          subscription_policies?: Json | null
          tags?: Json | null
          discovered_at?: string
          last_synced_at?: string | null
          created_at?: string
        }
      }
      alert_history: {
        Row: {
          id: string
          org_id: string
          alert_rule_id: string
          tenant_id: string
          subscription_id: string | null
          severity: string
          title: string
          message: string
          current_value: number
          threshold_value: number
          status: string
          acknowledged_at: string | null
          acknowledged_by: string | null
          resolved_at: string | null
          metadata: Json | null
          triggered_at: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          alert_rule_id: string
          tenant_id: string
          subscription_id?: string | null
          severity: string
          title: string
          message: string
          current_value: number
          threshold_value: number
          status?: string
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          resolved_at?: string | null
          metadata?: Json | null
          triggered_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          alert_rule_id?: string
          tenant_id?: string
          subscription_id?: string | null
          severity?: string
          title?: string
          message?: string
          current_value?: number
          threshold_value?: number
          status?: string
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          resolved_at?: string | null
          metadata?: Json | null
          triggered_at?: string
          created_at?: string
        }
      }
      azure_resources: {
        Row: {
          id: string
          org_id: string
          tenant_id: string
          subscription_id: string
          resource_id: string
          resource_name: string
          resource_type: string
          resource_group: string
          location: string | null
          sku: string | null
          kind: string | null
          tags: Json
          provisioning_state: string | null
          power_state: string | null
          properties: Json
          discovered_at: string
          last_synced_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          tenant_id: string
          subscription_id: string
          resource_id: string
          resource_name: string
          resource_type: string
          resource_group: string
          location?: string | null
          sku?: string | null
          kind?: string | null
          tags?: Json
          provisioning_state?: string | null
          power_state?: string | null
          properties?: Json
          discovered_at?: string
          last_synced_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          tenant_id?: string
          subscription_id?: string
          resource_id?: string
          resource_name?: string
          resource_type?: string
          resource_group?: string
          location?: string | null
          sku?: string | null
          kind?: string | null
          tags?: Json
          provisioning_state?: string | null
          power_state?: string | null
          properties?: Json
          discovered_at?: string
          last_synced_at?: string
          created_at?: string
          updated_at?: string
        }
      }
      optimization_recommendations: {
        Row: {
          id: string
          org_id: string
          tenant_id: string
          subscription_id: string
          recommendation_type: string
          severity: string
          title: string
          description: string
          resource_id: string
          resource_name: string
          resource_type: string
          resource_group: string
          location: string | null
          current_monthly_cost_usd: number
          potential_monthly_savings_usd: number
          potential_annual_savings_usd: number
          metrics: Json
          suggested_action: string | null
          implementation_effort: string
          status: string
          dismissed_at: string | null
          dismissed_by: string | null
          implemented_at: string | null
          detected_at: string
          last_evaluated_at: string
          expires_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          tenant_id: string
          subscription_id: string
          recommendation_type: string
          severity?: string
          title: string
          description: string
          resource_id: string
          resource_name: string
          resource_type: string
          resource_group: string
          location?: string | null
          current_monthly_cost_usd?: number
          potential_monthly_savings_usd?: number
          potential_annual_savings_usd?: number
          metrics?: Json
          suggested_action?: string | null
          implementation_effort?: string
          status?: string
          dismissed_at?: string | null
          dismissed_by?: string | null
          implemented_at?: string | null
          detected_at?: string
          last_evaluated_at?: string
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          tenant_id?: string
          subscription_id?: string
          recommendation_type?: string
          severity?: string
          title?: string
          description?: string
          resource_id?: string
          resource_name?: string
          resource_type?: string
          resource_group?: string
          location?: string | null
          current_monthly_cost_usd?: number
          potential_monthly_savings_usd?: number
          potential_annual_savings_usd?: number
          metrics?: Json
          suggested_action?: string | null
          implementation_effort?: string
          status?: string
          dismissed_at?: string | null
          dismissed_by?: string | null
          implemented_at?: string | null
          detected_at?: string
          last_evaluated_at?: string
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      report_configurations: {
        Row: {
          id: string
          org_id: string
          name: string
          description: string | null
          schedule_type: 'daily' | 'weekly' | 'monthly' | 'quarterly'
          schedule_day_of_week: number | null
          schedule_day_of_month: number | null
          schedule_time: string
          tenant_ids: string[]
          subscription_ids: string[]
          service_categories: string[]
          date_range_type: 'last_7_days' | 'last_30_days' | 'last_month' | 'last_quarter' | 'custom'
          custom_start_date: string | null
          custom_end_date: string | null
          include_summary: boolean
          include_trend_chart: boolean
          include_breakdown_chart: boolean
          include_detailed_table: boolean
          include_recommendations: boolean
          recipient_emails: string[]
          is_active: boolean
          last_sent_at: string | null
          next_scheduled_at: string | null
          created_at: string
          created_by: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          name: string
          description?: string | null
          schedule_type: 'daily' | 'weekly' | 'monthly' | 'quarterly'
          schedule_day_of_week?: number | null
          schedule_day_of_month?: number | null
          schedule_time?: string
          tenant_ids?: string[]
          subscription_ids?: string[]
          service_categories?: string[]
          date_range_type?: 'last_7_days' | 'last_30_days' | 'last_month' | 'last_quarter' | 'custom'
          custom_start_date?: string | null
          custom_end_date?: string | null
          include_summary?: boolean
          include_trend_chart?: boolean
          include_breakdown_chart?: boolean
          include_detailed_table?: boolean
          include_recommendations?: boolean
          recipient_emails: string[]
          is_active?: boolean
          last_sent_at?: string | null
          next_scheduled_at?: string | null
          created_at?: string
          created_by?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          name?: string
          description?: string | null
          schedule_type?: 'daily' | 'weekly' | 'monthly' | 'quarterly'
          schedule_day_of_week?: number | null
          schedule_day_of_month?: number | null
          schedule_time?: string
          tenant_ids?: string[]
          subscription_ids?: string[]
          service_categories?: string[]
          date_range_type?: 'last_7_days' | 'last_30_days' | 'last_month' | 'last_quarter' | 'custom'
          custom_start_date?: string | null
          custom_end_date?: string | null
          include_summary?: boolean
          include_trend_chart?: boolean
          include_breakdown_chart?: boolean
          include_detailed_table?: boolean
          include_recommendations?: boolean
          recipient_emails?: string[]
          is_active?: boolean
          last_sent_at?: string | null
          next_scheduled_at?: string | null
          created_at?: string
          created_by?: string | null
          updated_at?: string
        }
      }
      report_history: {
        Row: {
          id: string
          org_id: string
          report_config_id: string | null
          report_name: string
          report_type: 'scheduled' | 'manual'
          date_range_start: string
          date_range_end: string
          pdf_url: string | null
          file_size_bytes: number | null
          sent_to_emails: string[]
          generation_status: 'pending' | 'generating' | 'completed' | 'failed'
          error_message: string | null
          generated_at: string
          generated_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          report_config_id?: string | null
          report_name: string
          report_type: 'scheduled' | 'manual'
          date_range_start: string
          date_range_end: string
          pdf_url?: string | null
          file_size_bytes?: number | null
          sent_to_emails?: string[]
          generation_status?: 'pending' | 'generating' | 'completed' | 'failed'
          error_message?: string | null
          generated_at?: string
          generated_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          report_config_id?: string | null
          report_name?: string
          report_type?: 'scheduled' | 'manual'
          date_range_start?: string
          date_range_end?: string
          pdf_url?: string | null
          file_size_bytes?: number | null
          sent_to_emails?: string[]
          generation_status?: 'pending' | 'generating' | 'completed' | 'failed'
          error_message?: string | null
          generated_at?: string
          generated_by?: string | null
          created_at?: string
        }
      }
      scheduled_reports: {
        Row: {
          id: string
          org_id: string
          tenant_id: string
          name: string
          frequency: string
          report_type: string
          recipients: string[]
          format: string
          enabled: boolean
          last_run_at: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          tenant_id: string
          name: string
          frequency: string
          report_type: string
          recipients: string[]
          format?: string
          enabled?: boolean
          last_run_at?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          tenant_id?: string
          name?: string
          frequency?: string
          report_type?: string
          recipients?: string[]
          format?: string
          enabled?: boolean
          last_run_at?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      organization_branding: {
        Row: {
          id: string
          org_id: string
          logo_url: string | null
          primary_color: string
          secondary_color: string
          company_name: string | null
          company_website: string | null
          company_address: string | null
          company_phone: string | null
          email_header_text: string | null
          email_footer_text: string | null
          report_header_text: string | null
          report_footer_text: string | null
          show_powered_by: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          logo_url?: string | null
          primary_color?: string
          secondary_color?: string
          company_name?: string | null
          company_website?: string | null
          company_address?: string | null
          company_phone?: string | null
          email_header_text?: string | null
          email_footer_text?: string | null
          report_header_text?: string | null
          report_footer_text?: string | null
          show_powered_by?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          logo_url?: string | null
          primary_color?: string
          secondary_color?: string
          company_name?: string | null
          company_website?: string | null
          company_address?: string | null
          company_phone?: string | null
          email_header_text?: string | null
          email_footer_text?: string | null
          report_header_text?: string | null
          report_footer_text?: string | null
          show_powered_by?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      notification_channels: {
        Row: {
          id: string
          org_id: string
          teams_webhook_url: string | null
          teams_enabled: boolean
          slack_webhook_url: string | null
          slack_enabled: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          teams_webhook_url?: string | null
          teams_enabled?: boolean
          slack_webhook_url?: string | null
          slack_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          teams_webhook_url?: string | null
          teams_enabled?: boolean
          slack_webhook_url?: string | null
          slack_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      notification_preferences: {
        Row: {
          id: string
          org_id: string
          quiet_hours_enabled: boolean
          quiet_hours_start: string
          quiet_hours_end: string
          quiet_hours_timezone: string
          digest_mode_enabled: boolean
          digest_frequency: 'daily' | 'weekly' | 'immediate'
          digest_delivery_time: string
          digest_delivery_day: number | null
          digest_delivery_timezone: string
          critical_alerts_bypass_quiet_hours: boolean
          high_alerts_bypass_quiet_hours: boolean
          include_resolved_alerts: boolean
          include_recommendations: boolean
          include_cost_summary: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          quiet_hours_enabled?: boolean
          quiet_hours_start?: string
          quiet_hours_end?: string
          quiet_hours_timezone?: string
          digest_mode_enabled?: boolean
          digest_frequency?: 'daily' | 'weekly' | 'immediate'
          digest_delivery_time?: string
          digest_delivery_day?: number | null
          digest_delivery_timezone?: string
          critical_alerts_bypass_quiet_hours?: boolean
          high_alerts_bypass_quiet_hours?: boolean
          include_resolved_alerts?: boolean
          include_recommendations?: boolean
          include_cost_summary?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          quiet_hours_enabled?: boolean
          quiet_hours_start?: string
          quiet_hours_end?: string
          quiet_hours_timezone?: string
          digest_mode_enabled?: boolean
          digest_frequency?: 'daily' | 'weekly' | 'immediate'
          digest_delivery_time?: string
          digest_delivery_day?: number | null
          digest_delivery_timezone?: string
          critical_alerts_bypass_quiet_hours?: boolean
          high_alerts_bypass_quiet_hours?: boolean
          include_resolved_alerts?: boolean
          include_recommendations?: boolean
          include_cost_summary?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      alert_digest_queue: {
        Row: {
          id: string
          org_id: string
          alert_history_id: string
          scheduled_for: string
          included_in_digest_at: string | null
          digest_batch_id: string | null
          alert_title: string
          alert_severity: string
          tenant_name: string
          current_cost: number | null
          triggered_at: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          alert_history_id: string
          scheduled_for: string
          included_in_digest_at?: string | null
          digest_batch_id?: string | null
          alert_title: string
          alert_severity: string
          tenant_name: string
          current_cost?: number | null
          triggered_at: string
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          alert_history_id?: string
          scheduled_for?: string
          included_in_digest_at?: string | null
          digest_batch_id?: string | null
          alert_title?: string
          alert_severity?: string
          tenant_name?: string
          current_cost?: number | null
          triggered_at?: string
          created_at?: string
        }
      }
      feature_requests: {
        Row: {
          id: string
          org_id: string
          user_id: string
          title: string
          description: string
          category: 'integration' | 'analytics' | 'alerts' | 'ui' | 'automation' | 'other'
          status: 'submitted' | 'under_review' | 'planned' | 'in_progress' | 'completed' | 'declined'
          priority: 'low' | 'medium' | 'high' | 'critical'
          estimated_delivery: string | null
          vote_count: number
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          title: string
          description: string
          category: 'integration' | 'analytics' | 'alerts' | 'ui' | 'automation' | 'other'
          status?: 'submitted' | 'under_review' | 'planned' | 'in_progress' | 'completed' | 'declined'
          priority?: 'low' | 'medium' | 'high' | 'critical'
          estimated_delivery?: string | null
          vote_count?: number
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string
          title?: string
          description?: string
          category?: 'integration' | 'analytics' | 'alerts' | 'ui' | 'automation' | 'other'
          status?: 'submitted' | 'under_review' | 'planned' | 'in_progress' | 'completed' | 'declined'
          priority?: 'low' | 'medium' | 'high' | 'critical'
          estimated_delivery?: string | null
          vote_count?: number
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      feature_votes: {
        Row: {
          id: string
          feature_request_id: string
          user_id: string
          org_id: string
          created_at: string
        }
        Insert: {
          id?: string
          feature_request_id: string
          user_id: string
          org_id: string
          created_at?: string
        }
        Update: {
          id?: string
          feature_request_id?: string
          user_id?: string
          org_id?: string
          created_at?: string
        }
      }
      user_sessions: {
        Row: {
          id: string
          user_id: string
          org_id: string
          session_token: string
          ip_address: string | null
          user_agent: string | null
          created_at: string
          last_activity_at: string
          expires_at: string
          terminated_at: string | null
          termination_reason: string | null
        }
        Insert: {
          id?: string
          user_id: string
          org_id: string
          session_token: string
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
          last_activity_at?: string
          expires_at: string
          terminated_at?: string | null
          termination_reason?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          org_id?: string
          session_token?: string
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
          last_activity_at?: string
          expires_at?: string
          terminated_at?: string | null
          termination_reason?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      calculate_next_digest_time: {
        Args: { p_org_id: string }
        Returns: string
      }
      terminate_expired_sessions: {
        Args: Record<string, never>
        Returns: void
      }
      terminate_idle_session: {
        Args: { p_session_token: string; p_reason?: string }
        Returns: void
      }
      update_session_activity: {
        Args: { p_session_token: string }
        Returns: void
      }
      cleanup_old_sessions: {
        Args: Record<string, never>
        Returns: void
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
