// This file will be auto-generated by Supabase CLI in production
// For now, we provide a basic type structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          subscription_plan: string
          subscription_status: string
          trial_ends_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          subscription_plan?: string
          subscription_status?: string
          trial_ends_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          subscription_plan?: string
          subscription_status?: string
          trial_ends_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          org_id: string
          email: string
          full_name: string | null
          role: string
          created_at: string
          last_login_at: string | null
        }
        Insert: {
          id: string
          org_id: string
          email: string
          full_name?: string | null
          role?: string
          created_at?: string
          last_login_at?: string | null
        }
        Update: {
          id?: string
          org_id?: string
          email?: string
          full_name?: string | null
          role?: string
          created_at?: string
          last_login_at?: string | null
        }
      }
      azure_tenants: {
        Row: {
          id: string
          org_id: string
          name: string
          azure_tenant_id: string
          azure_app_id: string
          azure_client_secret: string
          connection_status: string
          last_sync_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          name: string
          azure_tenant_id: string
          azure_app_id: string
          azure_client_secret: string
          connection_status?: string
          last_sync_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          name?: string
          azure_tenant_id?: string
          azure_app_id?: string
          azure_client_secret?: string
          connection_status?: string
          last_sync_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      cost_snapshots: {
        Row: {
          id: string
          org_id: string
          tenant_id: string
          subscription_id: string
          resource_id: string | null
          resource_name: string | null
          resource_type: string | null
          resource_group: string | null
          service_category: string | null
          location: string | null
          cost_usd: number
          date: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          tenant_id: string
          subscription_id: string
          resource_id?: string | null
          resource_name?: string | null
          resource_type?: string | null
          resource_group?: string | null
          service_category?: string | null
          location?: string | null
          cost_usd: number
          date: string
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          tenant_id?: string
          subscription_id?: string
          resource_id?: string | null
          resource_name?: string | null
          resource_type?: string | null
          resource_group?: string | null
          service_category?: string | null
          location?: string | null
          cost_usd?: number
          date?: string
          created_at?: string
        }
      }
      alert_rules: {
        Row: {
          id: string
          org_id: string
          tenant_id: string
          name: string
          type: string
          threshold_amount: number | null
          threshold_percent: number | null
          notification_channels: Json
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          tenant_id: string
          name: string
          type: string
          threshold_amount?: number | null
          threshold_percent?: number | null
          notification_channels: Json
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          tenant_id?: string
          name?: string
          type?: string
          threshold_amount?: number | null
          threshold_percent?: number | null
          notification_channels?: Json
          status?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
